# Stage 1: Build React App
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG REACT_APP_API_URL=https://motoexpert.proyectoscampus.top
ENV REACT_APP_API_URL=$REACT_APP_API_URL

ARG REACT_APP_WOMPI_PUBLIC_KEY
ENV REACT_APP_WOMPI_PUBLIC_KEY=$REACT_APP_WOMPI_PUBLIC_KEY

# 🚀 AGREGA ESTAS DOS LÍNEAS PARA EL ID DE GOOGLE
ARG REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]