services:
  db:
    image: postgres:18-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: MotoExpert
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database_backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - '3005:3000'
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_PASSWORD: '12345'
      DB_NAME: MotoExpert
      DB_PORT: 5432
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM_WHATSAPP: 'whatsapp:+14155238886'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: https://ungodly-outhouse-bondless.ngrok-free.dev
    ports:
      - '3001:3001'
    depends_on:
      - backend

  frontend-mobile:
    build:
      context: ./frontend-mobile
      args:
        REACT_APP_API_URL: https://ungodly-outhouse-bondless.ngrok-free.dev
    ports:
      - '3002:3002'
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http nginx:80
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - '4040:4040'
    depends_on:
      - nginx

volumes:
  postgres_data: